version: "3.7"

services:
    db:
        image: postgres:13-alpine
        restart: unless-stopped
        volumes:
            - data:/var/lib/postgresql/data
        env_file: ./.env.local #Here we are using the already existing .env.local file
        ports:
            - "5432:5432"
    admin:
        image: adminer
        restart: unless-stopped
        depends_on:
            - db
        ports:
            - 8080:8080

volumes:
    data:
