app = "shellphone-prod"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/buildpacks:20"

[build.args]
  QUIRREL_BASE_URL = "www.shellphone.app"
  HUSKY_SKIP_INSTALL = 1

[env]
  NODE_ENV = "production"
  AWS_SES_REGION = "eu-central-1"
  AWS_SES_FROM_EMAIL = "mokhtar@fss.dev"
  QUIRREL_API_URL = "https://queue.mokhtar.dev"
  QUIRREL_BASE_URL = "www.shellphone.app"
  APP_BASE_URL = "www.shellphone.app"

[deploy]
  release_command = "/app/node_modules/.bin/blitz prisma migrate deploy"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"

[[statics]]
guest_path = "/app/.next/static"
url_prefix = "/_next/static"

[[statics]]
guest_path = "/app/public/fonts"
url_prefix = "/fonts"
