name: CI

on: [push, pull_request]

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: "npm"
            - run: npm ci
            - run: npm run lint

    typecheck:
        name: Typecheck
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16
            - run: npm ci
            - run: npx tsc

    deploy_development:
        if: github.ref == 'refs/heads/master'
        needs: [lint, typecheck]
        name: Deploy development environment
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: superfly/flyctl-actions@master
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
              with:
                  args: "deploy --strategy rolling -c ./fly.dev.toml"
            - uses: appleboy/discord-action@master
              with:
                  webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
                  webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
                  args: "https://dev.shellphone.app deployed with commit `${{ github.event.head_commit.message }}` (`${{ github.sha }}`) from branch `${{ github.ref }}`"


    deploy_production:
        if: github.ref == 'refs/heads/production'
        needs: [lint, typecheck]
        name: Deploy production environment
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: superfly/flyctl-actions@master
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
              with:
                  args: "deploy --strategy rolling"
            - uses: appleboy/discord-action@master
              with:
                  webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
                  webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
                  args: "https://www.shellphone.app deployed with commit `${{ github.event.head_commit.message }}` (`${{ github.sha }}`) from branch `${{ github.ref }}`"
